import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const iranSans = localFont({
  src: [
    {
      path: "/fonts/IRANSansWebFaNum-Light.woff2",
      style: "normal",
    },
    {
      path: "/fonts/IRANSansXFaNum-Medium.woff2",
      style: "normal",
    },
  ],
  variable: "--font-iransans",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" >
      <body className={iranSans.variable} >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
