import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LayoutFooter from "@/components/layout/Footer";
import Header from "@/components/layout/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const iranSans = localFont({
  src: [
    {
      path: "/fonts/IRANSansWebFaNum-Light.woff2",
      style: "normal",
    },
    {
      path: "/fonts/IRANSansXFaNum-Medium.woff2",
      style: "normal",
    },
  ],
  variable: "--font-iransans",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" >
      <body className={iranSans.variable} >
        {/* 👉 Header  */}
        <Header />
        <main>
          {children}
        </main>
        {/* 👉 Footer  */}
        <LayoutFooter />
      </body>
    </html>
  );
}
